// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
}
export {}
